citibike_dbt:
  target: dev_local # setting default value
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: ./creds.json
      project: "cse-6242-sp22-nyatl"
      dataset: "DBT_DEV"
      threads: 32
      timeout_seconds: 300
      priority: interactive

    prod:
      type: bigquery
      method: service-account
      keyfile: ./creds.json
      project: "cse-6242-sp22-nyatl"
      dataset: "DBT_PROD"
      threads: 32
      timeout_seconds: 300
      priority: interactive

    dev_local:
      type: bigquery
      method: oauth
      project: "cse-6242-sp22-nyatl"
      dataset: "DBT_DEV"
      threads: 32
      timeout_seconds: 300
      priority: interactive