version: 2

sources:
  - name: weather
    project: cse-6242-sp22-nyatl
    dataset: WEATHER
    tables:
      - name: noaa_gsod_2013_onward

  - name: bigquery_public_data__noa_gsod
    project: bigquery-public-data
    dataset: noaa_gsod
    tables:
      - name: stations

  - name: geo
    project: cse-6242-sp22-nyatl
    dataset: GEO
    tables:
      - name: geo_data