name: 'Citibike Trip History: Extract AWS Zip & Load CSV to GCS'

on:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - 'main'

jobs:
  citibike_trip_history_EL:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Install python libraries
      run: |
        pip install --upgrade pip
        pip install --upgrade protobuf
        pip install boto3
        pip install google-cloud-storage google-cloud-bigquery

    - name: Extract from AWS, Load to GCS
      run: |
        python src/copy_aws_to_gcs.py \
          --aws_bucket tripdata \
          --aws_access_key ${{ secrets.AWS_ACCESS_KEY }} \
          --aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --project_id cse-6242-sp22-nyatl \
          --gcs_bucket citibike_trip_history \
          --aws_exclude_pattern '(JC-)|(\d{4}-\d{4})'
    
    - name: Load from GCS to GBQ
      run: python src/gcs_to_gbq.py
    
  citibike_trip_history_T:
    needs: citibike_trip_history_EL
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Install python libraries
      run: pip install --upgrade dbt-bigquery

    - name: dbt install deps
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt deps"
        dbt_project_folder: "citibike_dbt"

    - name: dbt run (target dev)
      uses: mwhitaker/dbt-action@master  
      with:
        dbt_command: "dbt run --profiles-dir . --target dev"
        dbt_project_folder: "citibike_dbt"
      env:
        DBT_BIGQUERY_TOKEN: ${{ secrets.GCP_CREDENTIALS }}

    - name: dbt test
      uses: mwhitaker/dbt-action@master  
      with:
        dbt_command: "dbt test --profiles-dir . --target dev"
        dbt_project_folder: "citibike_dbt"
      env:
        DBT_BIGQUERY_TOKEN: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: dbt run (target prod)
      uses: mwhitaker/dbt-action@master  
      with:
        dbt_command: "dbt run --profiles-dir . --target prod"
        dbt_project_folder: "citibike_dbt"
      env:
        DBT_BIGQUERY_TOKEN: ${{ secrets.GCP_CREDENTIALS }}
  
    - name: dbt docs generate
      id: dbt-docs-generate
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt docs generate --profiles-dir . --target prod"
        dbt_project_folder: "citibike_dbt"
      env:
        DBT_BIGQUERY_TOKEN: ${{ secrets.GCP_CREDENTIALS }}

    - name: Convert dbt docs to static page
      run: python src/dbt_utility.py

  build_github_pages:
    needs: citibike_trip_history_T
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: build_github_pages
        with:
          route: POST /repos/${{ github.repository }}/pages/builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo ${{ steps.build_github_pages.outputs }}"